#!/usr/bin/python3


import sys
import time


def factorize(n):
    """
    Factorize a number n into two smaller factors.
    """
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return i, n // i
    return None, None

def main():
    if len(sys.argv) != 2:
        print("Usage: {} <file>".format(sys.argv[0]))
        sys.exit(1)

    input_file = sys.argv[1]

    try:
        with open(input_file, 'r') as f:
            for line in f:
                n = int(line.strip())
                p, q = factorize(n)
                if p is not None:
                    print("{}={}*{}".format(n, p, q))
                else:
                    print("Unable to factorize {}".format(n))
    except FileNotFoundError:
        print("File not found: {}".format(input_file))
        sys.exit(1)

if __name__ == "__main__":
    main()
